- name: install required apt packages
  apt:
    name:
      - acl   # needed to prevent errors when building as unprivileged user via become
      - jq
    state: present
    update_cache: yes

- name: Create unprivileged pokt user
  user:
    name: "{{ pokt_user }}"
    password: '*'   # pw is locked/disabled.  key auth only + passwordless sudo
    state: present
    shell: /bin/bash
    createhome: yes
    home: /home/{{ pokt_user }}
    #groups:
    # - sudo     # fixme: least privilege start/stop pokt services

- name: Create go project dirs for pokt user
  file:
    path: "{{ pokt_user_dir }}/{{ item }}"
    owner: '{{ pokt_user }}'
    group: '{{ pokt_user }}'
    state: directory
    mode: '0755'
  loop:
    - 'go'
    - 'go/bin'
    - 'go/src'
    - 'go/src/github.com/pokt-network'

- name: copy .profile
  template:
    src: 'profile.j2'
    dest: '{{ pokt_user_dir }}/.profile'
    owner: '{{ pokt_user }}'
    group: '{{ pokt_user }}'
    mode: '0600'

- name: Install golang
  import_tasks: install_golang.yml

- name: Build and install pokt binary from source
  import_tasks: build_pokt.yml
  tags: "build_pokt"

- name: Configure systemd
  import_tasks: configure_systemd.yml
  tags: "configure_systemd"

- name: Configure pokt keychain and config, etc.
  import_tasks: configure_pokt.yml
  tags: "configure_pokt"

- name: Update sudoers to permit pokt user to start/stop pocket service
  community.general.sudoers:
    name: allow-pocket-start-stop
    state: present
    user: "{{ pokt_user }}"
    commands: /bin/systemctl stop pocket,/bin/systemctl start pocket,/bin/systemctl restart pocket

- name: Deploy update_public_ip.sh script
  template:
    src: "update_public_ip.sh.j2"
    dest: "{{ pokt_user_dir }}/update_public_ip.sh"
    owner: "{{ pokt_user }}"
    group: "{{ pokt_user }}"
    mode: 0750
  tags: "pokt_update_public_ip"

- name: Schedule update_public_ip.sh script to run daily
  ansible.builtin.cron:
    name: "daily script run"
    user: "{{ pokt_user }}"
    minute: "20"
    hour: "4"
    job: "{{ pokt_user_dir }}/update_public_ip.sh"

