- name: Main
  hosts: '{{ target }}'
  gather_facts: false
  #vars_files:
  #  - '{{ var_file }}'
  roles:
    - role: 'docker_server'
      tags: 'docker_server'
      become: true

    - role: 'base_server'
      tags: 'base_server'
      become: true

    #- role: 'portainer'
    #  tags: 'portainer'
    #  become: true

    #- role: 'pokt_docker'
    #  tags: 'pokt_docker'
    #  become: true

    - role: 'monitor'
      tags: 'monitor'
      become: true
    
    - role: 'pokt_dev'
      tags: 'pokt_dev'
      become: true
    
  handlers:
      - name: restart sshd
        service:
          name: sshd
          state: restarted
        become: true
      
      - name: daemon-reload
        command: systemctl daemon-reload
        become: true
      
      - name: restart pocket
        service:
          name: pocket
          state: restarted
        become: true
      
      - name: restart docker
        service:
          name: docker
          state: restarted
        become: true
