{
 "title": "Pocket",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Network Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tendermint_consensus_height{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Peers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_p2p_peers{job=\"pocket\"}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "tendermint_p2p_peers{job=\"pocket\"}"
    }
   ]
  },
  {
   "title": "Block time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tendermint_consensus_block_interval_seconds{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unconfirmed Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "expr": "tendermint_mempool_size{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Block size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "tendermint_consensus_block_size_bytes{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    { "expr": "tendermint_consensus_num_txs{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Missing Validators",
   "type": "timeseries",
   "description": "Validators who did not sign last block",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "tendermint_consensus_missing_validators{}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Relay Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Relays",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "pocketcore_service_relay_count_for_0001{job=\"pocket\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pocketcore_service_relay_count_for_0021{job=\"pocket\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pocketcore_service_relay_count_for_0046{job=\"pocket\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relay Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(pocketcore_service_avg_relay_time_for_0001_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(pocketcore_service_avg_relay_time_for_0021_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(pocketcore_service_avg_relay_time_for_0046_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unique Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "pocketcore_service_sessions_count_for_0001{}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pocketcore_service_sessions_count_for_0021{}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pocketcore_service_sessions_count_for_0046{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Servicer Tokens Earned",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "pocketcore_service_tokens_earned_for_0001{}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pocketcore_service_tokens_earned_for_0021{}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pocketcore_service_tokens_earned_for_0046{}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}