- name: install apt packages required for building pokt binary
  apt:
    name:
      - make
      - build-essential
      - gcc
      - git
      - jq
      - chrony
      - curl
      - acl   # needed to prevent errors when building as unprivileged user via become
      - lz4   # for unarchiving snapshot data
    state: present
    update_cache: yes

- name: Install pokt daemon from source
  block:
    - name: Clone pokt repo
      become: yes
      become_user: "{{ pokt_user }}"
      git:
        repo: '{{ repo }}'
        dest: '{{ pokt_user_dir }}/go/src/github.com/pokt-network/pocket-core'
        version: '{{ pokt_release_tag }}'
        update: yes
        force: yes
        depth: 1

    - name: build and install pokt binary
      become: yes
      become_user: "{{ pokt_user }}"
      command: "go build -o {{ pokt_user_dir }}/go/bin/pocket"
      args: 
        chdir: "{{ pokt_user_dir }}/go/src/github.com/pokt-network/pocket-core/app/cmd/pocket_core"
      environment:
        PATH: "{{ path }}"
        GOPATH: "{{ pokt_user_dir }}/go"


      
